---
- become: yes
  tasks:
    - name: Echo "helloworld"
      command: echo helloworld
    - name: delete file
      file:
        path: /tmp/test1
        state: absent
      
    - name: copy file
      copy:
        src: /tmp/test2/a.txt
        dest: /tmp/test3/a.txt
        remote_src: yes
    - name: restart
      systemd:
        name: apache2
        state: restarted
        enabled : yes
